version: '3.9'

services:
  app:
    container_name: app-preview
    restart: always
    command: yarn start
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    networks:
      project_development:
        aliases:
          - backend
    ports:
      - ${PORT}:${PORT}
      - 9229:9229 # Debug port
    volumes:
      - .:/app
      - /node_modules
    env_file:
      - ./.env

networks:
  project_development:

volumes:
  project_development:
